name: rispar_credit_simulator
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.6
  get_it: ^7.2.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: ^0.3.0 
   
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/gifs/

  fonts:

    - family: Aftika
      fonts:
        - asset: assets/fonts/aftika_bold.ttf

    - family: Vayu
      fonts:
        - asset: assets/fonts/VayuSans-Bold.ttf

    - family: Abitare
      fonts:
        - asset: assets/fonts/AbitareSans-700.ttf

    - family: Eloquia
      fonts:
        - asset: assets/fonts/Eloquia-ExtraBold.otf

    - family: Cabrion
      fonts:
        - asset: assets/fonts/Cabrion-Regular.ttf
        - asset: assets/fonts/Cabrion-Bold.ttf
          weight: 700
           

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700